import turtle,time
turtle.getscreen()
turtle.speed(100)
turtle.pendown()
turtle.forward(200)
turtle.left(90)
turtle.forward(300)
turtle.left(90)
turtle.forward(400)
turtle.left(90)
turtle.forward(300)
turtle.left(90)
turtle.forward(200)
turtle.penup()
turtle.goto(200,200)
turtle.pendown()
turtle.backward(400)
turtle.penup()
turtle.goto(-200,100)
turtle.pendown()
turtle.forward(400)
turtle.penup()
turtle.penup()
turtle.goto(-200,100)
turtle.goto(0,100)
turtle.pendown()
turtle.circle(50)
turtle.penup()
turtle.goto(-200,200)

turtle.color("orange")
turtle.begin_fill()
turtle.forward(400)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(400)
turtle.end_fill()

turtle.goto(-200,0)
turtle.color("green")
turtle.begin_fill()
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()


for _ in range(24):
        turtle.color('blue')
        turtle.penup()
        turtle.goto(0,150)
        turtle.left(15)
        turtle.pendown()
        turtle.forward(50)
turtle.mainloop()
